#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

# shellcheck disable=SC1091
source scripts/lib/domains.sh
# shellcheck disable=SC1091
source scripts/lib/tty.sh

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
step() { printf '\n\033[1;36m── Step %s/%s: %s ──\033[0m\n\n' "$1" "$2" "$3"; }

prompt() {
  local var="$1" default="$2" label="$3"
  local value
  if [ -r /dev/tty ]; then
    read -r -p "${label} [${default}]: " value </dev/tty
  else
    read -r -p "${label} [${default}]: " value
  fi
  printf -v "${var}" '%s' "${value:-$default}"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "error: '$1' is required" >&2
    exit 1
  }
}

TOTAL_STEPS=5

ensure_tty_stdin

require_cmd docker
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  echo "error: docker compose is required" >&2
  exit 1
fi

if has_configured_domains 2>/dev/null || [ -f .env ]; then
  bold "Existing configuration detected"
  if has_configured_domains 2>/dev/null; then
    echo "Configured domains:"
    while IFS='|' read -r domain hostname selector; do
      echo "  - ${domain} (${hostname}, selector: ${selector})"
    done < <(list_domains)
  fi
  echo
  echo "  1) Add another domain  (recommended — runs add-domain.sh)"
  echo "  2) Reconfigure from scratch  (replaces domains.conf and .env)"
  echo "  3) Cancel"
  echo
  _choice=""
  if [ -r /dev/tty ]; then
    read -r -p "Choose [1]: " _choice </dev/tty
  else
    read -r -p "Choose [1]: " _choice
  fi
  _choice="${_choice:-1}"
  case "${_choice}" in
    1)
      exec bash "${ROOT}/scripts/add-domain.sh"
      ;;
    2)
      echo
      echo "Reconfiguring from scratch..."
      ;;
    3)
      echo "Cancelled."
      exit 0
      ;;
    *)
      echo "error: invalid choice" >&2
      exit 1
      ;;
  esac
fi

bold "DIY Mailer — setup wizard"
echo "This wizard will:"
echo "  1. Configure your sending domain(s) and DKIM keys"
echo "  2. Set network access for your apps"
echo "  3. Build and start Postfix + OpenDKIM"
echo "  4. Print DKIM public keys and DNS records to publish"
echo
echo "Press Enter at each prompt to accept the default in [brackets]."
echo

step 1 "${TOTAL_STEPS}" "Sending domains"

DOMAIN_COUNT=1
if [ -r /dev/tty ]; then
  read -r -p "How many sending domains? [1]: " _count </dev/tty
else
  read -r -p "How many sending domains? [1]: " _count
fi
_count="${_count:-1}"
if [[ "${_count}" =~ ^[0-9]+$ ]] && [ "${_count}" -gt 0 ]; then
  DOMAIN_COUNT="${_count}"
fi

echo
if [ "${DOMAIN_COUNT}" -gt 1 ]; then
  echo "Multiple domains share one sending IP — use a single SMTP hostname for A + PTR + HELO."
  echo "It can live on any domain you control (e.g. mail.example.com)."
fi
prompt SHARED_HOSTNAME "mail.example.com" "Shared SMTP hostname (A record + PTR)"

: > domains.conf
echo "# Generated by scripts/setup.sh — domain|hostname|selector" >> domains.conf

for ((i = 1; i <= DOMAIN_COUNT; i++)); do
  echo
  if [ "${DOMAIN_COUNT}" -gt 1 ]; then
    bold "Domain ${i} of ${DOMAIN_COUNT}"
    if [ "${i}" -eq 1 ]; then
      echo "(Primary domain — default envelope identity; HELO uses shared hostname above)"
    fi
  else
    bold "Your sending domain"
  fi

  prompt DOMAIN "example.com" "Domain name (From: noreply@DOMAIN)"
  prompt SELECTOR "mail" "DKIM selector"

  echo "${DOMAIN}|${SHARED_HOSTNAME}|${SELECTOR}" >> domains.conf

  if [ "${i}" -eq 1 ]; then
    PRIMARY_DOMAIN="${DOMAIN}"
    PRIMARY_HOSTNAME="${SHARED_HOSTNAME}"
    PRIMARY_SELECTOR="${SELECTOR}"
    EMAIL_FROM_DEFAULT="noreply@${DOMAIN}"
    EMAIL_FROM_NAME_DEFAULT="${DOMAIN}"
  fi
done

step 2 "${TOTAL_STEPS}" "Network access"
echo "Where should Postfix listen? Apps on this host connect here to send mail."
echo "  127.0.0.1:25:25      localhost only (dev)"
echo "  <internal-ip>:25:25   host internal IP (production — set SMTP_HOST to same IP in apps)"
echo "  0.0.0.0:25:25        all interfaces (not recommended without TLS + SASL)"
prompt SMTP_BIND "127.0.0.1:25:25" "Docker port mapping (host:container)"

echo
echo "Relay networks — CIDRs allowed to send without SMTP authentication:"
prompt SMTP_RELAY_MYNETWORKS "127.0.0.0/8 172.16.0.0/12 172.20.0.0/16 10.0.0.0/8" "mynetworks"

echo
if [ -r /dev/tty ]; then
  read -r -p "Attach to existing Docker network? (name, empty to skip): " DOCKER_NETWORK </dev/tty
else
  read -r -p "Attach to existing Docker network? (name, empty to skip): " DOCKER_NETWORK
fi
DOCKER_NETWORK="${DOCKER_NETWORK:-}"

echo
prompt EMAIL_FROM "${EMAIL_FROM_DEFAULT}" "Default From address (for test script)"
prompt EMAIL_FROM_NAME "${EMAIL_FROM_NAME_DEFAULT}" "Default From display name"

SMTP_HOST="${SMTP_BIND%%:*}"
SMTP_PORT="${SMTP_BIND#*:}"
SMTP_PORT="${SMTP_PORT%%:*}"

cat > .env <<EOF
MAIL_DOMAIN=${PRIMARY_DOMAIN}
MAIL_HOSTNAME=${PRIMARY_HOSTNAME}
DKIM_SELECTOR=${PRIMARY_SELECTOR}
SMTP_BIND=${SMTP_BIND}
SMTP_RELAY_MYNETWORKS="${SMTP_RELAY_MYNETWORKS}"
DOCKER_NETWORK=${DOCKER_NETWORK:-}
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_SECURE=0
SMTP_USER=
SMTP_PASS=
EMAIL_FROM=${EMAIL_FROM}
EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
EOF

mkdir -p .data/dkim .data/mailer

step 3 "${TOTAL_STEPS}" "Build and start containers"
${COMPOSE} up -d --build

if [ -n "${DOCKER_NETWORK}" ] && [ "${DOCKER_NETWORK}" != "mailer-internal" ]; then
  if docker network inspect "${DOCKER_NETWORK}" >/dev/null 2>&1; then
    bold "Connecting mailer to network: ${DOCKER_NETWORK}"
    docker network connect "${DOCKER_NETWORK}" "$(${COMPOSE} ps -q mailer)" 2>/dev/null || true
    echo "Tip: set SMTP_HOST=mailer in your app when using a shared Docker network"
  fi
fi

sleep 2

step 4 "${TOTAL_STEPS}" "DKIM public keys"
echo "Publish each TXT record at your DNS provider (details in Step 5)."
bash scripts/show-dkim.sh || true

step 5 "${TOTAL_STEPS}" "DNS records and app integration"
bash scripts/check-dns.sh --generate

bold "Application .env (add to each app on this host)"
echo "SMTP_HOST must be the internal IP from SMTP_BIND — mailer is not on the public internet."
grep -E '^SMTP_|^EMAIL_' .env

echo
bold "Next steps"
echo "  1. Publish the DNS records above at your registrar"
echo "  2. Verify DNS:  bash scripts/check-dns.sh"
echo "  3. Send a test: bash scripts/send-test.sh you@example.com"
echo "  4. Add a domain: bash scripts/add-domain.sh"
echo
bold "Done. See README.md for SPF, DMARC, bounce handling, and deliverability."
